### ISSUE TITLE
Add support for Difficult Terrain Obstacle types

### ISSUE THREAD

**Issue by MorganVergara** [PepijnMC/ElevationDragRuler#18]
The Enhanced Terrain Layer module provides several Obstacle classifications in addition to terrain type. See below:

![image](https://user-images.githubusercontent.com/30846057/166625892-975de7e9-1759-49cd-a37e-e5d08ca08f7a.png)

It would be great if the drag ruler integration supported those, as well as the basic terrain types.

**Comment by PepijnMC** [comment]
Drag Ruler (the base module for which my module is an addon) will be getting a substantial overhaul to its API for which I will have to rewrite a lot of code. So I will be holding off on all smaller update till then.

**Comment by PepijnMC** [comment]
I have opted to overwrite the environments from ETL to let them work better with the rules of dnd5e. All of the standard environments are still there but I am using the obstacles to represent effects from the few spells in the game that introduce extra movement costs instead of defining the area as difficult terrain like most spells do. The movement costs from these spells stack slightly different because they are not technically difficult terrain.

If the default ETL obstacles are really important to people I might include them again, but they don't really interact with dnd5e's rules and it felt like they were just bloating the list.
