### ISSUE TITLE
API: Elevation Ruler

### ISSUE THREAD

**Issue by caewok** [PepijnMC/ElevationDragRuler#67]
In [Elevation Ruler](https://github.com/caewok/fvtt-elevation-ruler), I borrowed your idea about using the Token HUD to switch between walk/fly/burrow. So first I wanted to say thanks for coming up with the idea! Also, if you wanted to have other features of this module work with Elevation Ruler, let me know if I can assist. I also am the author of [Terrain Mapper](https://github.com/caewok/fvtt-terrain-mapper) and there may be some things worth coordinating on that as well.

**Comment by PepijnMC** [comment]
This module is heavily dependent on Drag Ruler, which handles all the actual ruler stuff for this module. If I were to make a dnd5e specific extension for Elevation Ruler (which I assume is system agnostic?) it would likely become its own module. Not that I have the time these days :(.

Regarding Terrain Mapper, good to see an alternative to Enhanced Terrain Layer is available! This module used to depend on Terrain Ruler (extension of Drag Ruler) and ETL's API which are both no longer up to date as you know. But compatibility with Terrain Mapper would be better to coordinate with Drag Ruler / Terrain Ruler rather than this specific dnd5e extension module, or with a currently non-existent dnd5e module for Elevation Ruler.
